const SUCCESS = "00";
const FAILURE = "99";
const NOT_FOUND = "97";
const UNAUTHORIZED = "98";
const INVALID_CREDENTIALS = "51";
const INVALID_TOKEN = "50";
const USER_ALREADY_EXIST = "52";
const INSUFFICIENT_DATA = "53";

export const ResponseCodes = {
	SUCCESS,
	FAILURE,
	INSUFFICIENT_DATA,
	INVALID_CREDENTIALS,
	INVALID_TOKEN,
	NOT_FOUND,
	UNAUTHORIZED,
	USER_ALREADY_EXIST,
};
